awesome_flask_webapp/blueprints/main.py
# -*- coding: utf-8 -*-
from flask import Blueprint, render_template, url_for, request, flash, current_app, abort, redirect, send_from_directory

from flask_login import login_required, current_user

from awesome_flask_webapp.utils import redirect_back
from awesome_flask_webapp.decorators import confirm_required, permission_required
from awesome_flask_webapp.models import Notification, Post, Comment, Category, Tag, Collect, Follow, User
from awesome_flask_webapp.extensions import db, cache
from awesome_flask_webapp.forms.main import CommentForm, PostForm
from awesome_flask_webapp.notifications import push_new_comment_notification, push_new_collector_notification


main_bp = Blueprint('main', __name__)


@main_bp.route('/')
def index():
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['AWESOME_POST_PER_PAGE']
    pagination = Post.query.order_by(Post.timestamp.desc()).paginate(page, per_page)
    posts = pagination.items
    return render_template('main/index.html', pagination=pagination, posts=posts)


@main_bp.route('/post/new', methods=['GET', 'POST'])
@login_required
@confirm_required
@permission_required('POST')
def new_post():
    form = PostForm()

    if form.validate_on_submit():
        title = form.title.data
        category = Category.query.get_or_404(form.category.data)
        body = form.body.data

        post = Post(title=title, body=body, category=category, author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('Post created', 'success')
        return redirect(url_for('user.index', user_id=current_user.id))

    return render_template('main/new_post.html', form=form)


@main_bp.route('/post/<int:post_id>/edit', methods=['GET', 'POST'])
@login_required
@confirm_required
@permission_required('POST')
def edit_post(post_id):
    post = Post.query.get_or_404(post_id)
    if current_user != post.author:
        abort(403)

    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.category = Category.query.get(form.category.data)
        post.body = form.body.data

        db.session.commit()
        flash('Post updated.', 'success')
        return redirect(url_for('user.index', user_id=current_user.id))

    form.title.data = post.title
    form.category.data = post.category.id
    form.body.data = post.body

    return render_template('main/edit_post.html', form=form)


@main_bp.route('/post/<int:post_id>/delete', methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)

    if current_user != post.author and not current_user.can('MODERATE'):
        abort(403)

    db.session.delete(post)
    db.session.commit()
    flash('Post deleted.', 'success')
    return redirect_back()


@main_bp.route('/post/<int:post_id>')
def show_post(post_id):
    post = Post.query.get_or_404(post_id)
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['AWESOME_COMMENT_PER_PAGE']
    pagination = Comment.query.with_parent(post).order_by(Comment.timestamp.desc()).paginate(page, per_page)
    comments = pagination.items

    comment_form = CommentForm()

    return render_template('main/post.html', pagination=pagination, post=post, comments=comments,
                           comment_form=comment_form)


@main_bp.route('/post/<int:post_id>/set-comment', methods=['POST'])
@login_required
def set_comment(post_id):
    post = Post.query.get_or_404(post_id)
    if current_user != post.author:
        abort(403)

    if post.can_comment:
        post.can_comment = False
        flash('Post comment disabled.', 'info')
    else:
        post.can_comment = True
        flash('Post comment enabled.', 'info')
    db.session.commit()
    return redirect(url_for('main.show_post', post_id=post_id))


@main_bp.route('/post/<int:post_id>/comment/new', methods=["POST"])
@login_required
@permission_required('COMMENT')
def new_comment(post_id):
    post = Post.query.get_or_404(post_id)
    page = request.args.get('page', 1, type=int)
    form = CommentForm()

    if form.validate_on_submit():
        body = form.body.data
        author = current_user._get_current_object()
        comment = Comment(body=body, author=author, post=post)

        replied_id = request.args.get('reply')
        if replied_id:
            comment.replied = Comment.query.get_or_404(replied_id)
            if comment.replied.author.receive_comment_notification:
                push_new_comment_notification(post_id=post_id, receiver=comment.replied.author)

        db.session.add(comment)
        db.session.commit()
        flash("Comment published.", 'success')

        if current_user is not post.author and post.author.receive_comment_notification:
            push_new_comment_notification(post_id=current_user.id, receiver=post.author, page=page)

        return redirect(url_for('.show_post', post_id=post_id, page=page))

    flash('Invalid comment.', 'warning')
    return redirect(url_for('main.show_post', post_id=post.id, page=page))


@main_bp.route('/reply/comment/<int:comment_id>')
@login_required
@permission_required('COMMENT')
def reply_comment(comment_id):
    comment = Comment.query.get_or_404(comment_id)
    return redirect(url_for('main.show_post', post_id=comment.post_id, reply=comment_id, author=comment.author.name)
                    + '#comment-form')


@main_bp.route('/delete/comment/<int:comment_id>', methods=['POST'])
@login_required
def delete_comment(comment_id):
    comment = Comment.query.get_or_404(comment_id)
    if current_user != comment.author and current_user != comment.post.author and not current_user.can('MODERATE'):
        abort(403)
    db.session.delete(comment)
    db.session.commit()
    flash('Comment deleted.', 'info')
    if request.args.get('next'):
        return redirect_back()
    return redirect(url_for('main.show_post', post_id=comment.post_id) + '#comments')


@main_bp.route('/collect/<int:post_id>', methods=['POST'])
@login_required
@confirm_required
@permission_required('COLLECT')
def collect(post_id):
    post = Post.query.get_or_404(post_id)
    if current_user.is_collecting(post):
        flash('Already collecting', 'info')
        return redirect(url_for('main.show_post', post_id=post_id))

    current_user.collect(post)
    flash('Post collected.', 'success')
    if current_user != post.author and post.author.receive_collect_notification:
        push_new_collector_notification(collector=current_user, post_id=post.id, receiver=post.author)
    return redirect(url_for('main.show_post', post_id=post_id))


@main_bp.route('/uncollect/<int:post_id>', methods=['POST'])
@login_required
def uncollect(post_id):
    post = Post.query.get_or_404(post_id)
    if not current_user.is_collecting(post):
        flash('Not collecting.', 'info')
        return redirect(url_for('main.show_post', post_id=post.id))

    current_user.uncollect(post)
    flash('Post uncollected.', 'success')
    return redirect(url_for('main.show_post', post_id=post_id))


@main_bp.route('/post/<int:post_id>/collectors')
@cache.cached(timeout=60)
def show_collectors(post_id):
    post = Post.query.get_or_404(post_id)
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['AWESOME_USER_PER_PAGE']
    pagination = Collect.query.with_parent(post).order_by(Collect.timestamp.desc()).paginate(page, per_page)
    collects = pagination.items
    return render_template('main/collectors.html', pagination=pagination, collects=collects, post=post)


@main_bp.route('/category/<int:category_id>')
@cache.cached(timeout=60)
def show_category(category_id):
    category = Category.query.get_or_404(category_id)
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['AWESOME_POST_PER_PAGE']
    pagination = Post.query.with_parent(category).order_by(Post.timestamp.desc()).paginate(page, per_page)
    posts = pagination.items
    return render_template('main/category.html', pagination=pagination, posts=posts, category=category)


@main_bp.route('/notifications')
@login_required
def show_notifications():
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['AWESOME_NOTIFICATION_PER_PAGE']
    notifications = Notification.query.with_parent(current_user)
    filter_rule = request.args.get('filter')
    if filter_rule == 'unread':
        notifications = notifications.filter_by(is_read=False)

    pagination = notifications.order_by(Notification.timestamp.desc()).paginate(page, per_page)
    notifications = pagination.items
    return render_template('main/notifications.html', pagination=pagination, notifications=notifications)


@main_bp.route('/notification/read/<int:notification_id>', methods=['POST'])
@login_required
def read_notification(notification_id):
    notification = Notification.query.get_or_404(notification_id)
    if current_user != notification.receiver:
        abort(403)

    notification.is_read = True
    db.session.commit()
    flash('Notification read.', 'success')
    return redirect(url_for('.show_notifications'))


@main_bp.route('/notification/read/all', methods=['POST'])
@login_required
def read_all_notifications():
    for notification in current_user.notifications:
        notification.is_read = True
    db.session.commit()
    flash('All notifications read.', 'success')
    return redirect(url_for('.show_notifications'))


@main_bp.route('/avatar/<path:filename>')
def get_avatar(filename):
    return send_from_directory(current_app.config['AVATARS_SAVE_PATH'], filename)


@main_bp.route('/about')
@cache.cached(timeout=3600 * 24)
def about():
    return render_template('main/about.html')


@main_bp.route('/search')
def search():
    q = request.args.get('q', '')
    if q == '':
        flash('Please enter something.', 'warning')
        return redirect_back()

    page = request.args.get('page', 1, type=int)

awesome_flask_webapp/blueprints/user.py
# -*- coding: utf-8 -*-
from flask import Blueprint, request, current_app, render_template, url_for, flash, redirect
from flask_login import current_user, login_required, fresh_login_required, logout_user

from awesome_flask_webapp.settings import Operations
from awesome_flask_webapp.extensions import db
from awesome_flask_webapp.models import User, Post, Collect
from awesome_flask_webapp.decorators import confirm_required, permission_required
from awesome_flask_webapp.utils import redirect_back, generate_token, validate_token
from awesome_flask_webapp.emails import send_change_email_email, send_reset_password_email
from awesome_flask_webapp.forms.user import EditProfileForm, ChangePasswordForm, ChangeEmailForm, \
    NotificationSettingForm, PublicCollectionsSettingForm, DeleteAccountForm
from awesome_flask_webapp.notifications import push_new_follower_notification


user_bp = Blueprint('user', __name__, url_prefix='/user')


@user_bp.route('/user/<int:user_id>')
def index(user_id):
    user = User.query.get_or_404(user_id)
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['AWESOME_POST_PER_PAGE']
    pagination = Post.query.with_parent(user).order_by(Post.timestamp.desc()).paginate(page, per_page)
    posts = pagination.items
    return render_template('user/index.html', pagination=pagination, user=user, posts=posts)


@user_bp.route('/<int:user_id>/collections')
def show_collections(user_id):
    user = User.query.get_or_404(user_id)

    if not user.public_collections:
        return render_template('user/collections.html', user=user)

    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['AWESOME_POST_PER_PAGE']
    pagination = Collect.query.with_parent(user).order_by(Collect.timestamp.desc()).paginate(page, per_page)
    collects = pagination.items

    return render_template('user/collections.html', pagination=pagination, user=user, collects=collects)


@user_bp.route('/<int:user_id>/following')
def show_followings(user_id):
    user = User.query.get_or_404(user_id)
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['AWESOME_USER_PER_PAGE']
    pagination = user.followings.paginate(page, per_page)
    follows = pagination.items
    return render_template('user/followings.html', user=user, pagination=pagination, follows=follows)


@user_bp.route('/<int:user_id>/followers')
def show_followers(user_id):
    user = User.query.get_or_404(user_id)
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['AWESOME_USER_PER_PAGE']
    pagination = user.followers.paginate(page, per_page)
    follows = pagination.items
    return render_template('user/followers.html', user=user, pagination=pagination, follows=follows)


@user_bp.route('/follow/<int:user_id>', methods=['POST'])
@login_required
@confirm_required
@permission_required('FOLLOW')
def follow(user_id):
    user = User.query.get_or_404(user_id)
    if current_user.is_following(user):
        flash('Already followed.', 'info')
        return redirect(url_for('user.index', user_id=user_id))

    current_user.follow(user)
    flash('User followed.', 'success')
    if user.receive_follow_notification:
        push_new_follower_notification(follower=current_user, receiver=user)
    return redirect_back()


@user_bp.route('/unfollow/<int:user_id>', methods=['POST'])
@login_required
def unfollow(user_id):
    user = User.query.get_or_404(user_id)

    if not current_user.is_following(user):
        flash('Not follow yet.', 'info')
        return redirect(url_for('user.index', user_id=user_id))

    current_user.unfollow(user)
    flash('User unfollowed.', 'info')
    return redirect_back()


@user_bp.route('/settings/profile', methods=['GET' ,'POST'])
@login_required
def edit_profile():
    form = EditProfileForm()

    if form.validate_on_submit():
        current_user.username = form.username.data
        current_user.name = form.name.data
        current_user.location = form.location.data
        current_user.bio = form.bio.data
        db.session.commit()
        flash('Profile updated.', 'success')
        return redirect(url_for('user.index', user_id=current_user.id))

    form.username.data = current_user.username
    form.name.data = current_user.name
    form.location.data = current_user.location
    form.bio.data = current_user.bio

    return render_template('user/settings/edit_profile.html', form=form)



@user_bp.route('/settings/change-password', methods=['GET', 'POST'])
@fresh_login_required
def change_password():
    form = ChangePasswordForm()

    if form.validate_on_submit():
        if current_user.validate_password(form.old_password.data):
            current_user.set_password(form.password.data)
            db.session.commit()
            flash('Password changed.', 'success')
            return redirect(url_for('user.index', user_id=current_user.id))
        else:
            flash('Old Password invalid.', 'warning')

    return render_template('user/settings/change_password.html', form=form)


@user_bp.route('/settings/change-email', methods=['GET', 'POST'])
@fresh_login_required
def change_email():
    form = ChangeEmailForm()

    if form.validate_on_submit():
        token = generate_token(user=current_user, operation=Operations.CHANGE_EMAIL, new_email=form.email.data)
        send_change_email_email(user=current_user, token=token, to=form.email.data)
        flash('Confirm Email sent.', 'info')
        return redirect(url_for('user.index', user_id=current_user.id))

    return render_template('user/settings/change_email.html', form=form)


@user_bp.route('/change-email-confirm/<token>')
@login_required
def change_email_confirm(token):
    if validate_token(user=current_user, token=token, operation=Operations.CHANGE_EMAIL):
        flash('Email updated.', 'success')
        return redirect(url_for('user.index', user_id=current_user.id))
    else:
        flash('Token invalid or expired.', 'warning')
        return redirect(url_for('user.change_email'))


@user_bp.route('/settings/notification', methods=['GET', 'POST'])
@login_required
def notification_setting():
    form = NotificationSettingForm()

    if form.validate_on_submit():
        current_user.receive_collect_notification = form.receive_collect_notification.data
        current_user.receive_comment_notification = form.receive_comment_notification.data
        current_user.receive_follow_notification = form.receive_follow_notification.data
        db.session.commit()
        flash('Notifications setting updated.', 'success')
        return redirect(url_for('user.index', user_id=current_user.id))

    return render_template('user/settings/edit_notification.html', form=form)


@user_bp.route('/settings/privacy', methods=['GET', 'POST'])
@login_required
def privacy_setting():
    form = PublicCollectionsSettingForm()

    if form.validate_on_submit():
        current_user.public_collections = form.public_collections.data
        db.session.commit()
        flash('Privacy settings updated.', 'success')
        return redirect(url_for('.index', user_id=current_user.id))

    form.public_collections.data = current_user.public_collections
    return render_template('user/settings/edit_privacy.html', form=form)


@user_bp.route('/settings/account/delete', methods=['GET', 'POST'])
@fresh_login_required
def delete_account():
    form = DeleteAccountForm()

    if form.validate_on_submit():
        db.session.delete(current_user._get_current_object())
        db.session.commit()
        flash('Goodbye!', 'success')
        logout_user()
        return redirect(url_for('main.index'))

    return render_template('user/settings/delete_account.html', form=form)

awesome_flask_webapp/templates/user/_header.html
{% from 'macros.html' import follow_area with context %}
{% from 'bootstrap/nav.html' import render_nav_item %}

<div class="row">
    <div class="col-md-3">
        <img class="img-fluid rounded  avatar-l" src="{{ url_for('main.get_avatar', filename=user.avatar_l) }}">
    </div>
    <div class="col-md-9">
        <h1>{{ user.name }}
            <small class="text-muted">{{ user.username }}</small>
            {% if current_user == user %}
                <a class="btn btn-outline-primary btn-sm" href="{{ url_for('user.edit_profile') }}">Edit profile</a>
            {% endif %}
        </h1>
        {% if user.bio %}
            <p>{{ user.bio }}</p>
        {% endif %}
        <p>
            {% if user.location %}
                <span class="oi oi-map-marker"></span>
                <a href="https://map.baidu.com/search/{{ user.location }}"
                   target="_blank">{{ user.location|truncate(30) }}</a>&nbsp;&nbsp;
            {% endif %}
            <span class="oi oi-calendar"></span>
            {{ moment(user.member_since).format('LL') }}
        </p>

        <div class="float-left">
            {{ follow_area(user) }}
        </div>
    </div>
</div>
<div class="user-nav">
    <ul class="nav nav-tabs">
        {{ render_nav_item('user.index', 'Post', user.posts|length, user_id=user.id) }}
        {{ render_nav_item('user.show_collections', 'Collections', (user.collections if user.public_collections)|length
                            , user_id=user.id) }}
        {{ render_nav_item('user.show_followings', 'Followings', user.followings.count() - 1, user_id=user.id) }}
        {{ render_nav_item('user.show_followers', 'Followers', user.followers.count() - 1, user_id=user.id) }}
    </ul>
</div>

awesome_flask_webapp/templates/user/collections.html
 {% extends 'base.html' %}
{% from 'bootstrap/pagination.html' import render_pagination %}

{% block title %}{{ user.name }}{% endblock %}

{% block content %}
    {% include 'user/_header.html' %}

    <div class="row">
        <div class="col-md-10 mx-auto">
            {% if collects %}
                {% for collect in collects %}
                    <h3 class="text-primary">
                        <a href="{{ url_for('main.show_post', post_id=collect.collected.id) }}">{{ collect.collected.title }}</a>
                    </h3>
                    <p>
                        {{ collect.collected.body|striptags|truncate }}
                        <small><a href="{{ url_for('main.show_post', post_id=collect.collected.id) }}">Read More</a></small>
                    </p>
                    <small>
                        <span class="float-right" >
                             {{ moment(collect.collected.timestamp).format('LL') }}
                         </span>
                    </small>
                    {% if not loop.last %}
                        <br>
                        <hr>
                    {% endif %}
                {% endfor %}
            {% else %}
                <div class="tip text-center">
                    <h3>No collection.</h3>
                </div>
            {% endif %}
        </div>
    </div>
    {% if posts %}
        <div class="page-footer">
            {% if pagination.pages > 1 %}
                {{ render_pagination(pagination, align='center') }}
            {% endif %}
        </div>
    {% endif %}
{% endblock %}

awesome_flask_webapp/templates/user/followers.html
{% extends 'base.html' %}
{% from 'bootstrap/pagination.html' import render_pagination %}
{% from 'macros.html' import user_card with context %}

{% block title %}{{ user.name }}'s followers {% endblock %}

{% block content %}
    {% include 'user/_header.html' %}
    <div class="row">
        <div class="col-md-12">
            {% if follows|length != 1 %}
                {% for follow in follows %}
                    {% if follow.follower != user %}
                        {{ user_card(user=follow.follower) }}
                    {% endif %}
                {% endfor %}
            {% else %}
                <div class="tip">
                    <h3>No follower.</h3>
                </div>
            {% endif %}
        </div>
    </div>
    {% if follows|length != 1 %}
        <div class="page-footer">
            {% if pagination.pages > 1 %}
                {{ render_pagination(pagination, align='center') }}
            {% endif %}
        </div>
    {% endif %}
{% endblock %}

awesome_flask_webapp/templates/user/followings.html
{% extends 'base.html' %}
{% from 'bootstrap/pagination.html' import render_pagination %}
{% from 'macros.html' import user_card with context %}

{% block title %}{{ user.name }}'s followings{% endblock %}

{% block content %}
    {% include 'user/_header.html' %}
    <div class="row">
        <div class="col-md-12">
            {% if follows|length != 1 %}
                {% for follow in follows %}
                    {% if follow.followed != user %}
                        {{ user_card(user=follow.followed) }}
                    {% endif %}
                {% endfor %}
            {% else %}
                <div class="tip">
                    <h3>No following.</h3>
                </div>
            {% endif %}
        </div>
    </div>
    {% if follows|length != 1 %}
        <div class="page-footer">
            {% if pagination.pages > 1 %}
                {{ render_pagination(pagination, align='center') }}
            {% endif %}
        </div>
    {% endif %}
{% endblock %}

awesome_flask_webapp/templates/user/index.html
 {% extends 'base.html' %}
{% from 'bootstrap/pagination.html' import render_pagination %}

{% block title %}{{ user.name }}{% endblock %}

{% block content %}
    {% include 'user/_header.html' %}

    <div class="row">
        <div class="col-md-11 mx-auto">
            {% if posts %}
                {% for post in posts %}
                    <div class="row">
                        <div class="col-md-9">
                            <h3 class="text-primary">
                                <a href="{{ url_for('main.show_post', post_id=post.id) }}">{{ post.title }}</a>
                             </h3>
                            <p>
                                {{ post.body|striptags|truncate(100) }}
                                <small><a href="{{ url_for('main.show_post', post_id=post.id) }}">Read More</a></small>
                            </p>
                            <small>
                                <span class="float-right">
                                    {{ moment(post.timestamp).format('LL') }}
                                </span>
                            </small>
                        </div>
                        <div class="col-md-2" style="margin:auto">
                            {% if current_user == post.author %}
                                <a class="btn btn-outline-primary btn-sm"
                                   href="{{ url_for('main.edit_post', post_id=post.id) }}">Edit </a>
                                <a class="btn btn-outline-warning btn-sm" hef="#" data-toggle="modal"
                                   data-target="#deletePostModal"
                                   data-href="{{ url_for('main.delete_post', post_id=post.id) }}">Delete</a>
                            {% endif %}
                        </div>
                    </div>
                    {% if not loop.last %}
                        <hr>
                    {% endif %}
                {% endfor %}
            {% else %}
                <div class="tip text-center">
                    <h3>No post.</h3>
                    {% if user == current_user %}
                        <a class="btn btn-link" href="{{ url_for('main.new_post') }}">Create New Post.</a>
                    {% endif %}
                </div>
            {% endif %}
        </div>
    </div>
    {% if posts %}
        <div class="page-footer">
            {% if pagination.pages > 1 %}
                {{ render_pagination(pagination, align='center') }}
            {% endif %}
        </div>
    {% endif %}

    <!-- Delete Post Modal-->
    <div class="modal fade" id="deletePostModal">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Delete Confirm</h5>
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>
                <div class="modal-body">
                    <p>Are you sure to delete this post? </p>
                    <form class="inline float-right delete-post-form" method="post" action="">
                        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                        <button type="button" class="btn btn-primary btn-sm" data-dismiss="modal">Cancel</button>
                        <button type="submit" class="btn btn-warning btn-sm">Delete</button>
                    </form>
                </div>
            </div>
        </div>
    </div>


{% endblock %}