awesome_flask_webapp/forms/main.py
# -*- coding: utf-8 -*-
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField, SelectField
from wtforms.validators import DataRequired, Length, Optional, URL, ValidationError
from flask_ckeditor import CKEditorField

from awesome_flask_webapp.models import Category


class TagForm(FlaskForm):
    tag = StringField('Add Tag (use space to separate)', validators=[Optional(), Length(1, 20)])
    submit = SubmitField()


class CategoryForm(FlaskForm):
    category = StringField('Name', validators=[DataRequired(), Length(1, 30)])
    submit = SubmitField()

    def validate_name(self, field):
        if Category.query.filter_by(name=field.data).first():
            raise ValidationError('Category already in use.')


class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired(), Length(1, 100)])
    category = SelectField('Category', coerce=int, default=1)
    body = CKEditorField('Body', validators=[DataRequired()])
    submit = SubmitField()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.category.choices = [(category.id, category.name)
                                 for category in Category.query.order_by(Category.name).all()]


class CommentForm(FlaskForm):
    body = TextAreaField('', validators=[DataRequired()])
    submit = SubmitField()


class LinkForm(FlaskForm):
    name = StringField('Name', validators=[DataRequired(), Length(1, 100)])
    url = StringField('Url', validators=[DataRequired(), Length(1, 255), URL()])
    submit = SubmitField()

awesome_flask_webapp/blueprints/ajax.py
# -*- coding: utf-8 -*-
"""
    ajax（）方法对应的视图函数
"""
from flask import Blueprint, render_template, jsonify
from flask_login import current_user

from awesome_flask_webapp.models import User, Post, Notification
from awesome_flask_webapp.notifications import push_new_follower_notification

ajax_bp = Blueprint('ajax', __name__, url_prefix='/ajax')


#获取用户资料
@ajax_bp.route('/profile/<int:user_id>')
def get_profile(user_id):
    user = User.query.get_or_404(user_id)
    return render_template('main/profile.html', user=user)


#关注用户
@ajax_bp.route('/follow/<int:user_id>', methods=['POST'])
def follow(user_id):
    if not current_user.is_authenticated:
        return jsonify(message='Login required.'), 403
    if not current_user.confirmed:
        return jsonify(message='Confirm required.'), 400
    if not current_user.can('COLLECT'):
        return jsonify(message='No permission.'), 403

    user = User.query.get_or_404(user_id)
    if current_user.is_following(user):
        return jsonify(message='Already followed.'), 400

    current_user.follow(user)
    if user.receive_follow_notification:
        push_new_follower_notification(follower=current_user, receiver=user)
    return jsonify(message='Author followed.')


#取消关注
@ajax_bp.route('/unfollow/<int:user_id>', methods=['POST'])
def unfollow(user_id):
    if not current_user.is_authenticated:
        return jsonify(message='Login required.'), 403

    user = User.query.get_or_404(user_id)
    if not current_user.is_following(user):
        return jsonify(message='Not follow yet.'), 400

    current_user.unfollow(user)
    return jsonify(message='Follow canceled.')



#关注者数量
@ajax_bp.route('/followers-count/<int:user_id>')
def followers_count(user_id):
    user = User.query.get_or_404(user_id)
    count = user.followers.count() - 1
    return jsonify(count=count)


#用于定时更新页面消息提醒数量，
@ajax_bp.route('/notification-count')
def notification_count():
    if not current_user.is_authenticated:
        return jsonify(message='Login required.'), 403

    count = Notification.query.with_parent(current_user).filter_by(is_read=False).count()
    return jsonify(count=count)

awesome_flask_webapp/blueprints/auth.py
# -*- coding: utf-8 -*-
import random

from flask import Blueprint, render_template, redirect, url_for, flash, Markup
from flask_login import login_user, logout_user, login_required, current_user, login_fresh, confirm_login

from awesome_flask_webapp.settings import Operations
from awesome_flask_webapp.extensions import db
from awesome_flask_webapp.forms.auth import LoginForm, RegisterForm
from awesome_flask_webapp.models import User, Role
from awesome_flask_webapp.utils import redirect_back, generate_token, validate_token
from awesome_flask_webapp.emails import send_confirm_email


auth_bp = Blueprint('auth', __name__)


@auth_bp.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm()

    if form.validate_on_submit():
        username = form.username.data
        email = form.email.data.lower()
        password = form.password.data

        user = User(username=username, email=email)
        user.set_password(password)
        db.session.add(user)
        db.session.commit()

        token = generate_token(user, Operations.CONFIRM)
        send_confirm_email(user, token)
        flash('Confirm Email sent, please check your inbox', 'info')
        login_user(user)
        return redirect(url_for('main.index'))

    flash(Markup('<a href="%s" class="btn  btn-primary btn-sm ">Register</a> a administrator account with confirmed email' % (
            url_for('auth.register_without_confirm'))), 'primary')

    return render_template('auth/register.html', form=form)


@auth_bp.route('/register-without-confirm')
def register_without_confirm():
    username = 'administrator%s' % random.randint(1, 10000)
    email = 'admin%s@blog.com' % random.randint(1, 100000)
    password = '123456'
    user = User(username=username, email=email)
    user.set_password(password)
    user.confirmed = True

    role = Role.query.filter_by(name='Administrator').first()
    user.role = role

    db.session.add(user)
    db.session.commit()
    login_user(user)
    flash('Administrator account created.', 'success')
    return redirect(url_for('main.index'))


@auth_bp.route('/confirm/<token>')
@login_required
def confirm(token):
    if current_user.confirmed:
        return redirect(url_for('main.index'))

    if validate_token(current_user, Operations.CONFIRM, token):
        current_user.confirmed = True
        flash('Account confirmed.', 'success')
        return redirect(url_for('main.index'))
    else:
        flash('Invalid or expired token.', 'danger')
        return redirect(url_for('auth.resend_confirm_email'))


@auth_bp.route('/resend-confirm-email')
@login_required
def resend_confirm_email():
    if current_user.confirmed:
        return redirect(url_for('main.index'))

    token = generate_token(current_user, Operations.CONFIRM)
    send_confirm_email(current_user, token)
    flash('Confirm email resent, please check.', 'info')
    return redirect(url_for('main.index'))


@auth_bp.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()

    if form.validate_on_submit():
        email = form.email.data.lower()
        password = form.password.data

        user = User.query.filter_by(email=email).first()
        if user is not None and user.validate_password(password):
            login_user(user, form.remember.data)
            flash('Login success', 'info')
            return redirect(url_for('main.index'))
        flash('Your email or password invalid.', 'warning')
    return render_template('auth/login.html', form=form)


@auth_bp.route('/logout')
def logout():
    logout_user()
    flash('Logout success.', 'info')
    return redirect(url_for('main.index'))


@auth_bp.route('/re-authenticate', methods=['GET', 'POST'])
@login_required
def re_authenticate():
    if login_fresh():
        return redirect(url_for('main.index'))

    form = LoginForm()
    if form.validate_on_submit() and current_user.validate_password(form.password.data):
        confirm_login()
        return redirect_back()

    return render_template('auth/login.html', form=form)

awesome_flask_webapp/blueprints/main.py
# -*- coding: utf-8 -*-
from flask import Blueprint, render_template, url_for, request, flash, current_app, abort, redirect, send_from_directory

from flask_login import login_required, current_user

from awesome_flask_webapp.utils import redirect_back
from awesome_flask_webapp.decorators import confirm_required, permission_required
from awesome_flask_webapp.models import Notification, Post, Comment, Category, Tag, Collect, Follow, User
from awesome_flask_webapp.extensions import db, cache
from awesome_flask_webapp.forms.main import CommentForm, PostForm
from awesome_flask_webapp.notifications import push_new_comment_notification, push_new_collector_notification


main_bp = Blueprint('main', __name__)


@main_bp.route('/')
def index():
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['AWESOME_POST_PER_PAGE']
    pagination = Post.query.order_by(Post.timestamp.desc()).paginate(page, per_page)
    posts = pagination.items
    return render_template('main/index.html', pagination=pagination, posts=posts)


@main_bp.route('/post/new', methods=['GET', 'POST'])
@login_required
@confirm_required
@permission_required('POST')
def new_post():
    form = PostForm()

    if form.validate_on_submit():
        title = form.title.data
        category = Category.query.get_or_404(form.category.data)
        body = form.body.data

        post = Post(title=title, body=body, category=category, author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('Post created', 'success')
        return redirect(url_for('user.index', user_id=current_user.id))

    return render_template('main/new_post.html', form=form)


@main_bp.route('/post/<int:post_id>/edit', methods=['GET', 'POST'])
@login_required
@confirm_required
@permission_required('POST')
def edit_post(post_id):
    post = Post.query.get_or_404(post_id)
    if current_user != post.author:
        abort(403)

    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.category = Category.query.get(form.category.data)
        post.body = form.body.data

        db.session.commit()
        flash('Post updated.', 'success')
        return redirect(url_for('user.index', user_id=current_user.id))

    form.title.data = post.title
    form.category.data = post.category.id
    form.body.data = post.body

    return render_template('main/edit_post.html', form=form)


@main_bp.route('/post/<int:post_id>/delete', methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)

    if current_user != post.author and not current_user.can('MODERATE'):
        abort(403)

    db.session.delete(post)
    db.session.commit()
    flash('Post deleted.', 'success')
    return redirect_back()


@main_bp.route('/post/<int:post_id>')
def show_post(post_id):
    post = Post.query.get_or_404(post_id)
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['AWESOME_COMMENT_PER_PAGE']
    pagination = Comment.query.with_parent(post).order_by(Comment.timestamp.desc()).paginate(page, per_page)
    comments = pagination.items

    comment_form = CommentForm()

    return render_template('main/post.html', pagination=pagination, post=post, comments=comments,
                           comment_form=comment_form)


@main_bp.route('/post/<int:post_id>/set-comment', methods=['POST'])
@login_required
def set_comment(post_id):
    post = Post.query.get_or_404(post_id)
    if current_user != post.author:
        abort(403)

    if post.can_comment:
        post.can_comment = False
        flash('Post comment disabled.', 'info')
    else:
        post.can_comment = True
        flash('Post comment enabled.', 'info')
    db.session.commit()
    return redirect(url_for('main.show_post', post_id=post_id))


@main_bp.route('/post/<int:post_id>/comment/new', methods=["POST"])
@login_required
@permission_required('COMMENT')
def new_comment(post_id):
    post = Post.query.get_or_404(post_id)
    page = request.args.get('page', 1, type=int)
    form = CommentForm()

    if form.validate_on_submit():
        body = form.body.data
        author = current_user._get_current_object()
        comment = Comment(body=body, author=author, post=post)

        replied_id = request.args.get('reply')
        if replied_id:
            comment.replied = Comment.query.get_or_404(replied_id)
            if comment.replied.author.receive_comment_notification:
                push_new_comment_notification(post_id=post_id, receiver=comment.replied.author)

        db.session.add(comment)
        db.session.commit()
        flash("Comment published.", 'success')

        if current_user is not post.author and post.author.receive_comment_notification:
            push_new_comment_notification(post_id=current_user.id, receiver=post.author, page=page)

        return redirect(url_for('.show_post', post_id=post_id, page=page))

    flash('Invalid comment.', 'warning')
    return redirect(url_for('main.show_post', post_id=post.id, page=page))


@main_bp.route('/reply/comment/<int:comment_id>')
@login_required
@permission_required('COMMENT')
def reply_comment(comment_id):
    comment = Comment.query.get_or_404(comment_id)
    return redirect(url_for('main.show_post', post_id=comment.post_id, reply=comment_id, author=comment.author.name)
                    + '#comment-form')


@main_bp.route('/delete/comment/<int:comment_id>', methods=['POST'])
@login_required
def delete_comment(comment_id):
    comment = Comment.query.get_or_404(comment_id)
    if current_user != comment.author and current_user != comment.post.author and not current_user.can('MODERATE'):
        abort(403)
    db.session.delete(comment)
    db.session.commit()
    flash('Comment deleted.', 'info')
    if request.args.get('next'):
        return redirect_back()
    return redirect(url_for('main.show_post', post_id=comment.post_id) + '#comments')


@main_bp.route('/collect/<int:post_id>', methods=['POST'])
@login_required
@confirm_required
@permission_required('COLLECT')
def collect(post_id):
    post = Post.query.get_or_404(post_id)
    if current_user.is_collecting(post):
        flash('Already collecting', 'info')
        return redirect(url_for('main.show_post', post_id=post_id))

    current_user.collect(post)
    flash('Post collected.', 'success')
    if current_user != post.author and post.author.receive_collect_notification:
        push_new_collector_notification(collector=current_user, post_id=post.id, receiver=post.author)
    return redirect(url_for('main.show_post', post_id=post_id))


@main_bp.route('/uncollect/<int:post_id>', methods=['POST'])
@login_required
def uncollect(post_id):
    post = Post.query.get_or_404(post_id)
    if not current_user.is_collecting(post):
        flash('Not collecting.', 'info')
        return redirect(url_for('main.show_post', post_id=post.id))

    current_user.uncollect(post)
    flash('Post uncollected.', 'success')
    return redirect(url_for('main.show_post', post_id=post_id))


@main_bp.route('/post/<int:post_id>/collectors')
@cache.cached(timeout=60)
def show_collectors(post_id):
    post = Post.query.get_or_404(post_id)
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['AWESOME_USER_PER_PAGE']
    pagination = Collect.query.with_parent(post).order_by(Collect.timestamp.desc()).paginate(page, per_page)
    collects = pagination.items
    return render_template('main/collectors.html', pagination=pagination, collects=collects, post=post)


@main_bp.route('/category/<int:category_id>')
@cache.cached(timeout=60)
def show_category(category_id):
    category = Category.query.get_or_404(category_id)
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['AWESOME_POST_PER_PAGE']
    pagination = Post.query.with_parent(category).order_by(Post.timestamp.desc()).paginate(page, per_page)
    posts = pagination.items
    return render_template('main/category.html', pagination=pagination, posts=posts, category=category)


@main_bp.route('/notifications')
@login_required
def show_notifications():
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['AWESOME_NOTIFICATION_PER_PAGE']
    notifications = Notification.query.with_parent(current_user)
    filter_rule = request.args.get('filter')
    if filter_rule == 'unread':
        notifications = notifications.filter_by(is_read=False)

    pagination = notifications.order_by(Notification.timestamp.desc()).paginate(page, per_page)
    notifications = pagination.items
    return render_template('main/notifications.html', pagination=pagination, notifications=notifications)


@main_bp.route('/notification/read/<int:notification_id>', methods=['POST'])
@login_required
def read_notification(notification_id):
    notification = Notification.query.get_or_404(notification_id)
    if current_user != notification.receiver:
        abort(403)

    notification.is_read = True
    db.session.commit()
    flash('Notification read.', 'success')
    return redirect(url_for('.show_notifications'))


@main_bp.route('/notification/read/all', methods=['POST'])
@login_required
def read_all_notifications():
    for notification in current_user.notifications:
        notification.is_read = True
    db.session.commit()
    flash('All notifications read.', 'success')
    return redirect(url_for('.show_notifications'))


@main_bp.route('/avatar/<path:filename>')
def get_avatar(filename):
    return send_from_directory(current_app.config['AVATARS_SAVE_PATH'], filename)


@main_bp.route('/about')
@cache.cached(timeout=3600 * 24)
def about():
    return render_template('main/about.html')


@main_bp.route('/search')
def search():
    q = request.args.get('q', '')
    if q == '':
        flash('Please enter something.', 'warning')
        return redirect_back()

    page = request.args.get('page', 1, type=int)

awesome_flask_webapp/templates/main/_comment.html
<div class="comments" id="comments">
    <h3>
        {{ comments|length }} Comments
        <small>
            <a href="{{ url_for('main.show_post', post_id=post.id, page=pagination.pages or 1) }}">latest</a>
        </small>
        {% if current_user == post.author %}
            <form class="inline" method="post" action="{{ url_for('main.set_comment', post_id=post.id) }}">
                <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                <button type="submit" class="btn btn-sm btn-outline-primary  float-right">
                    {% if post.can_comment %}Disable{% else %}Enable{% endif %} Comment
                </button>
            </form>

        {% endif %}
    </h3>
    <hr>
    {% if comments %}
        {% for comment in comments %}
            <div class="comment">
                <div class="comment-thumbnail">
                    <a href="{{ url_for('user.index', user_id=comment.author.id) }}">
                        <img class="rounded avatar-s profile-popover"
                             data-href="{{ url_for('ajax.get_profile', user_id=comment.author.id) }}"
                            src="{{ url_for('main.get_avatar', filename=comment.author.avatar_m) }}">
                    </a>
                </div>
                <div class="comment-body">
                    <h6>
                        <a class="profile-popover" href="{{ url_for('user.index', user_id=comment.author.id) }}"
                           data-href="{{ url_for('ajax.get_profile', user_id=comment.author.id) }}">
                            {{ comment.author.name }}
                        </a>
                        {% if comment.author == post.author %}
                            <span class="badge badge-light">Author</span>
                        {% endif %}
                         &nbsp;&nbsp;
                        <small data-toggle="tooltip" data-placement="top" data-timestamp="{{ comment.timestamp }}"
                               data-delay="250">
                            {{ moment(comment.timestamp).fromNow(refresh=True) }}
                        </small>
                        {% if current_user.is_authenticated %}
                            <span class="float-right">
                                <div class="dropdown">
                                    <button type="button" class="btn btn-sm btn-light" data-toggle="dropdown">
                                        <span class="oi oi-ellipses"></span>
                                    </button>

                                    <span class="dropdown-menu">
                                        {% if comment.author != current_user %}
                                            <a class="dropdown-item btn-sm"
                                               href="{{ url_for('main.reply_comment', comment_id=comment.id) }}">
                                                <span class="oi oi-comment-square"></span> Reply
                                            </a>
                                        {% endif %}
                                        {% if current_user == comment.author or current_user == post.author or
                                                current_user.can('MODERATE') %}
                                            <a class="dropdown-item btn-sm" data-toggle="modal" href="#!"
                                               data-href="{{ url_for('main.delete_comment', comment_id=comment.id) }}"
                                                data-target="#confirm-delete">
                                                <span class="oi oi-trash"></span>Delete
                                            </a>
                                        {% endif %}
                                    </span>
                                </div>
                            </span>
                        {% endif %}
                    </h6>
                    <p>
                        {% if comment.replied %}
                            Reply
                            <a href="{{ url_for('user.index', user_id=comment.author.id) }}">
                                {{ comment.replied.author.name }}
                            </a>:
                        {% endif %}
                        {{ comment.body }}
                    </p>
                </div>
                <hr>
            </div>
        {% endfor %}
    <div class="page-footer">
        {% if pagination.pages > 1 %}
            {{ render_pagination(pagination, align='center', size='sm') }}
        {% endif %}
        </div>
    {% else %}
        <div class="tip">
            <h5>No comment.</h5>
        </div>
    {% endif %}

    {% if post.can_comment %}
        {% if current_user.is_authenticated %}
            {% if current_user.can('COMMENT') %}
                {% if request.args.get('reply') %}
                    <div class="alert alert-dark">
                        Reply to: {{ request.args.get('author') }}
                        <a class="float-right" href="{{ url_for('main.show_post', post_id=post.id) }}">Cancel</a>
                    </div>
                {% endif %}
                <div class="comment-form-area">
                    <div class="comment-form-thumbnail">
                        {{ current_user.username }}
                    </div>
                    <div class="comment-form" id="comment-form">
                        {{ render_form(
                            comment_form,
                            action=url_for('main.new_comment', post_id=post.id, page=pagination.pages or 1,
                                            reply=request.args.get('reply')),
                            extra_classes="text-right" ) }}
                    </div>
                </div>
            {% else %}
                <p class="tip">No permission to comment.</p>
            {% endif %}
        {% else %}
            <p class="tip">
                <a href="{{ url_for('auth.login') }}">Login</a>
                or
                <a href="{{ url_for('auth.register') }}">Register</a> to comment.
            </p>
        {% endif %}
    {% else %}
        <p class="tip">Comment disabled.</p>
    {% endif %}
</div>

awesome_flask_webapp/templates/main/_post_sidebar.html
{% from 'macros.html' import follow_area with context %}

<div class="card bg-light mb-3 w-100 sidebar-card">
    <div class="card-body">
        <div class="row">
            <a href="{{ url_for('user.index', user_id=post.author.id) }}">
                <img class="sidebar-avatar rounded avatar-m"
                     src="{{ url_for('main.get_avatar', filename=post.author.avatar_m) }}">
            </a>

            <div class="sidebar-profile ">
                <h6 class="card-title">
                    <a href="{{ url_for('user.index', user_id=post.author.id) }}">
                               {{ post.author.name }}
                        </span>
                    </a>
                </h6>
                <a class="card-subtitle mb-2 btn btn-primary btn-sm"
                   href="{{ url_for('user.index', user_id=post.author.id) }}">
                    <span class="oi oi-home"></span> home
                </a>
                {{ follow_area(post.author) }}
            </div>
        </div>
    </div>
</div>
<div class="card bg-light mb-3 w-100">
    <div class="card-body">
        {% include 'main/_sidebar.html' %}
    </div>
</div>

awesome_flask_webapp/templates/main/post.html
{% extends 'base.html' %}
{% from 'bootstrap/form.html' import render_form %}
{% from 'bootstrap/pagination.html' import render_pagination %}

{% block title %} {{ post.title }} {% endblock %}

{% block content %}
    <div class="row">
        <div class="col-sm-9">
            <div class="page-header">
                <h1>{{ post.title }}</h1>
                <small>
                    Category: <a href="#">default</a>&nbsp;&nbsp;
                    Date: {{ moment(post.timestamp).format('LL') }}
                </small>
            </div>

            {{ post.body|safe }}
            <hr>
            <button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#shareModal">Share</button>
            {% if current_user.is_authenticated %}
                {% if current_user.is_collecting(post) %}
                    <form class="inline" method="post" action="{{ url_for('main.uncollect', post_id=post.id) }}">
                        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                        <button type="submit" class="btn btn-outline-secondary btn-sm">
                            <span class="oi oi-x"></span> Uncollect
                        </button>
                    </form>
                {% else%}
                    <form class="inline" method="post" action="{{ url_for('main.collect', post_id=post.id) }}">
                        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                        <button type="submit" class="btn btn-outline-primary btn-sm">
                        <span class="oi oi-star"></span> Collect
                        </button>
                    </form>
                {% endif%}
            {% else %}
                <form class="inline" method="post" action="{{ url_for('main.collect', post_id=post.id) }}">
                    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                    <button type="submit" class="btn btn-secondary btn-sm">
                        <span class="oi oi-star"></span> Collect
                    </button>
                </form>
            {% endif %}

            {% include 'main/_comment.html' %}
        </div>
        <div class="col-sm-3 ml-auto">
            {% include 'main/_post_sidebar.html' %}
        </div>
    </div>

    <!-- Share Modal -->
     <div class="modal fade" id="shareModal">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Permalink</h5>
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>
                <div class="modal-body">
                    <input class="form-control" value="{{ url_for('main.show_post', post_id=post.id, _external=True) }}"
                        readonly>
                </div>
            </div>
        </div>
    </div>
    <!-- Delete Modal -->
    <div class="modal fade" id="confirm-delete">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Delete Confirm</h5>
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>
                <div class="modal-body">
                    <p>Are you sure to delete this item? </p>
                    <form class="inline float-right delete-form" action="" method="post">
                        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                        <button type="submit" class="btn btn-warning">Delete</button>
                    </form>
                </div>
                </div>
            </div>
        </div>
    </div>


{% endblock content %}

awesome_flask_webapp/templates/main/profile.html
<div class="popup-card">
    <img class="rounded img-fluid avatar-s popup-avatar" src="{{ url_for('main.get_avatar', filename=user.avatar_m) }}">
    <div class="popup-profile">
        <h6>{{ user.name }}</h6>
        <p class="text-muted">{{ user.username }}
            {% if current_user.is_authenticated %}
                {% if current_user != user and current_user.is_followed_by(user) %}
                    {% if user.is_followed_by(current_user) %}
                        <span class="badge badge-light">Follow each other</span>
                    {% else %}
                        <span class="badge badge-light">Follows you</span>
                    {% endif %}
                {% endif %}
            {% endif %}
        </p>
    </div>
    <p class="card-text">
        <a href="{{ url_for('user.index', user_id=user.id) }}">
            <strong>{{ user.posts|length }}</strong> Posts
        </a>&nbsp;
        <a href="{{ url_for('user.show_followers', user_id=user.id) }}">
            <strong id="followers-count-{{ user.id }}"
                    data-href="{{ url_for('ajax.followers_count', user_id=user.id) }}">
                {{ user.followers.count() - 1 }}
            </strong> Followers
        </a>
    </p>
    <span>
        <a href="{{ url_for('user.index', user_id=user.id) }}" class="btn btn-primary btn-sm">Home</a>
        {% if current_user.is_authenticated %}
            {% if user != current_user %}
                <button data-id="{{ user.id }}"
                        data-href="{{ url_for('ajax.unfollow', user_id=user.id) }}"
                        class="{% if not current_user.is_following(user) %}hide{% endif %} btn btn-dark btn-sm unfollow-btn">
                    Unfollow
                </button>
                <button data-id="{{ user.id }}"
                        data-href="{{ url_for('ajax.follow', user_id=user.id) }}"
                        class="{% if current_user.is_following(user) %}hide{% endif %} btn btn-primary btn-sm follow-btn">
                    Follow
                </button>
            {% endif %}
        {% else %}
            <form class="inline" method="post"
                  action="{{ url_for('user.follow', user_id=user.id) }}">
                <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                <button type="submit" class="btn btn-primary btn-sm">Follow</button>
            </form>
        {% endif %}
    </span>
</div>