awesome_flask_webapp/blueprints/ajax.py
# -*- coding: utf-8 -*-
"""
    ajax（）方法对应的视图函数
"""
from flask import Blueprint, render_template, jsonify
from flask_login import current_user

from awesome_flask_webapp.models import User, Post, Notification
from awesome_flask_webapp.notifications import push_new_follower_notification

ajax_bp = Blueprint('ajax', __name__, url_prefix='/ajax')


#获取用户资料
@ajax_bp.route('/profile/<int:user_id>')
def get_profile(user_id):
    user = User.query.get_or_404(user_id)
    return render_template('main/profile.html', user=user)


#关注用户
@ajax_bp.route('/follow/<int:user_id>', methods=['POST'])
def follow(user_id):
    if not current_user.is_authenticated:
        return jsonify(message='Login required.'), 403
    if not current_user.confirmed:
        return jsonify(message='Confirm required.'), 400
    if not current_user.can('COLLECT'):
        return jsonify(message='No permission.'), 403

    user = User.query.get_or_404(user_id)
    if current_user.is_following(user):
        return jsonify(message='Already followed.'), 400

    current_user.follow(user)
    if user.receive_follow_notification:
        push_new_follower_notification(follower=current_user, receiver=user)
    return jsonify(message='Author followed.')


#取消关注
@ajax_bp.route('/unfollow/<int:user_id>', methods=['POST'])
def unfollow(user_id):
    if not current_user.is_authenticated:
        return jsonify(message='Login required.'), 403

    user = User.query.get_or_404(user_id)
    if not current_user.is_following(user):
        return jsonify(message='Not follow yet.'), 400

    current_user.unfollow(user)
    return jsonify(message='Follow canceled.')



#关注者数量
@ajax_bp.route('/followers-count/<int:user_id>')
def followers_count(user_id):
    user = User.query.get_or_404(user_id)
    count = user.followers.count() - 1
    return jsonify(count=count)


#用于定时更新页面消息提醒数量，
@ajax_bp.route('/notification-count')
def notification_count():
    if not current_user.is_authenticated:
        return jsonify(message='Login required.'), 403

    count = Notification.query.with_parent(current_user).filter_by(is_read=False).count()
    return jsonify(count=count)

awesome_flask_webapp/blueprints/auth.py
# -*- coding: utf-8 -*-
import random

from flask import Blueprint, render_template, redirect, url_for, flash, Markup
from flask_login import login_user, logout_user, login_required, current_user, login_fresh, confirm_login

from awesome_flask_webapp.settings import Operations
from awesome_flask_webapp.extensions import db
from awesome_flask_webapp.forms.auth import LoginForm, RegisterForm
from awesome_flask_webapp.models import User, Role
from awesome_flask_webapp.utils import redirect_back, generate_token, validate_token
from awesome_flask_webapp.emails import send_confirm_email


auth_bp = Blueprint('auth', __name__)


@auth_bp.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm()

    if form.validate_on_submit():
        username = form.username.data
        email = form.email.data.lower()
        password = form.password.data

        user = User(username=username, email=email)
        user.set_password(password)
        db.session.add(user)
        db.session.commit()

        token = generate_token(user, Operations.CONFIRM)
        send_confirm_email(user, token)
        flash('Confirm Email sent, please check your inbox', 'info')
        login_user(user)
        return redirect(url_for('main.index'))

    flash(Markup('<a href="%s" class="btn  btn-primary btn-sm ">Register</a> a administrator account with confirmed email' % (
            url_for('auth.register_without_confirm'))), 'primary')

    return render_template('auth/register.html', form=form)


@auth_bp.route('/register-without-confirm')
def register_without_confirm():
    username = 'administrator%s' % random.randint(1, 10000)
    email = 'admin%s@blog.com' % random.randint(1, 100000)
    password = '123456'
    user = User(username=username, email=email)
    user.set_password(password)
    user.confirmed = True

    role = Role.query.filter_by(name='Administrator').first()
    user.role = role

    db.session.add(user)
    db.session.commit()
    login_user(user)
    flash('Administrator account created.', 'success')
    return redirect(url_for('main.index'))


@auth_bp.route('/confirm/<token>')
@login_required
def confirm(token):
    if current_user.confirmed:
        return redirect(url_for('main.index'))

    if validate_token(current_user, Operations.CONFIRM, token):
        current_user.confirmed = True
        flash('Account confirmed.', 'success')
        return redirect(url_for('main.index'))
    else:
        flash('Invalid or expired token.', 'danger')
        return redirect(url_for('auth.resend_confirm_email'))


@auth_bp.route('/resend-confirm-email')
@login_required
def resend_confirm_email():
    if current_user.confirmed:
        return redirect(url_for('main.index'))

    token = generate_token(current_user, Operations.CONFIRM)
    send_confirm_email(current_user, token)
    flash('Confirm email resent, please check.', 'info')
    return redirect(url_for('main.index'))


@auth_bp.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()

    if form.validate_on_submit():
        email = form.email.data.lower()
        password = form.password.data

        user = User.query.filter_by(email=email).first()
        if user is not None and user.validate_password(password):
            login_user(user, form.remember.data)
            flash('Login success', 'info')
            return redirect(url_for('main.index'))
        flash('Your email or password invalid.', 'warning')
    return render_template('auth/login.html', form=form)


@auth_bp.route('/logout')
def logout():
    logout_user()
    flash('Logout success.', 'info')
    return redirect(url_for('main.index'))


@auth_bp.route('/re-authenticate', methods=['GET', 'POST'])
@login_required
def re_authenticate():
    if login_fresh():
        return redirect(url_for('main.index'))

    form = LoginForm()
    if form.validate_on_submit() and current_user.validate_password(form.password.data):
        confirm_login()
        return redirect_back()

    return render_template('auth/login.html', form=form)

awesome_flask_webapp/blueprints/main.py
# -*- coding: utf-8 -*-
from flask import Blueprint, render_template, url_for, request, flash, current_app, abort, redirect, send_from_directory

from flask_login import login_required, current_user

from awesome_flask_webapp.utils import redirect_back
from awesome_flask_webapp.decorators import confirm_required, permission_required
from awesome_flask_webapp.models import Notification, Post, Comment, Category, Tag, Collect, Follow, User
from awesome_flask_webapp.extensions import db, cache
from awesome_flask_webapp.forms.main import CommentForm, PostForm
from awesome_flask_webapp.notifications import push_new_comment_notification, push_new_collector_notification


main_bp = Blueprint('main', __name__)


@main_bp.route('/')
def index():
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['AWESOME_POST_PER_PAGE']
    pagination = Post.query.order_by(Post.timestamp.desc()).paginate(page, per_page)
    posts = pagination.items
    return render_template('main/index.html', pagination=pagination, posts=posts)


@main_bp.route('/post/new', methods=['GET', 'POST'])
@login_required
@confirm_required
@permission_required('POST')
def new_post():
    form = PostForm()

    if form.validate_on_submit():
        title = form.title.data
        category = Category.query.get_or_404(form.category.data)
        body = form.body.data

        post = Post(title=title, body=body, category=category, author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('Post created', 'success')
        return redirect(url_for('user.index', user_id=current_user.id))

    return render_template('main/new_post.html', form=form)


@main_bp.route('/post/<int:post_id>/edit', methods=['GET', 'POST'])
@login_required
@confirm_required
@permission_required('POST')
def edit_post(post_id):
    post = Post.query.get_or_404(post_id)
    if current_user != post.author:
        abort(403)

    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.category = Category.query.get(form.category.data)
        post.body = form.body.data

        db.session.commit()
        flash('Post updated.', 'success')
        return redirect(url_for('user.index', user_id=current_user.id))

    form.title.data = post.title
    form.category.data = post.category.id
    form.body.data = post.body

    return render_template('main/edit_post.html', form=form)


@main_bp.route('/post/<int:post_id>/delete', methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)

    if current_user != post.author and not current_user.can('MODERATE'):
        abort(403)

    db.session.delete(post)
    db.session.commit()
    flash('Post deleted.', 'success')
    return redirect_back()


@main_bp.route('/post/<int:post_id>')
def show_post(post_id):
    post = Post.query.get_or_404(post_id)
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['AWESOME_COMMENT_PER_PAGE']
    pagination = Comment.query.with_parent(post).order_by(Comment.timestamp.desc()).paginate(page, per_page)
    comments = pagination.items

    comment_form = CommentForm()

    return render_template('main/post.html', pagination=pagination, post=post, comments=comments,
                           comment_form=comment_form)


@main_bp.route('/post/<int:post_id>/set-comment', methods=['POST'])
@login_required
def set_comment(post_id):
    post = Post.query.get_or_404(post_id)
    if current_user != post.author:
        abort(403)

    if post.can_comment:
        post.can_comment = False
        flash('Post comment disabled.', 'info')
    else:
        post.can_comment = True
        flash('Post comment enabled.', 'info')
    db.session.commit()
    return redirect(url_for('main.show_post', post_id=post_id))


@main_bp.route('/post/<int:post_id>/comment/new', methods=["POST"])
@login_required
@permission_required('COMMENT')
def new_comment(post_id):
    post = Post.query.get_or_404(post_id)
    page = request.args.get('page', 1, type=int)
    form = CommentForm()

    if form.validate_on_submit():
        body = form.body.data
        author = current_user._get_current_object()
        comment = Comment(body=body, author=author, post=post)

        replied_id = request.args.get('reply')
        if replied_id:
            comment.replied = Comment.query.get_or_404(replied_id)
            if comment.replied.author.receive_comment_notification:
                push_new_comment_notification(post_id=post_id, receiver=comment.replied.author)

        db.session.add(comment)
        db.session.commit()
        flash("Comment published.", 'success')

        if current_user is not post.author and post.author.receive_comment_notification:
            push_new_comment_notification(post_id=current_user.id, receiver=post.author, page=page)

        return redirect(url_for('.show_post', post_id=post_id, page=page))

    flash('Invalid comment.', 'warning')
    return redirect(url_for('main.show_post', post_id=post.id, page=page))


@main_bp.route('/reply/comment/<int:comment_id>')
@login_required
@permission_required('COMMENT')
def reply_comment(comment_id):
    comment = Comment.query.get_or_404(comment_id)
    return redirect(url_for('main.show_post', post_id=comment.post_id, reply=comment_id, author=comment.author.name)
                    + '#comment-form')


@main_bp.route('/delete/comment/<int:comment_id>', methods=['POST'])
@login_required
def delete_comment(comment_id):
    comment = Comment.query.get_or_404(comment_id)
    if current_user != comment.author and current_user != comment.post.author and not current_user.can('MODERATE'):
        abort(403)
    db.session.delete(comment)
    db.session.commit()
    flash('Comment deleted.', 'info')
    if request.args.get('next'):
        return redirect_back()
    return redirect(url_for('main.show_post', post_id=comment.post_id) + '#comments')


@main_bp.route('/collect/<int:post_id>', methods=['POST'])
@login_required
@confirm_required
@permission_required('COLLECT')
def collect(post_id):
    post = Post.query.get_or_404(post_id)
    if current_user.is_collecting(post):
        flash('Already collecting', 'info')
        return redirect(url_for('main.show_post', post_id=post_id))

    current_user.collect(post)
    flash('Post collected.', 'success')
    if current_user != post.author and post.author.receive_collect_notification:
        push_new_collector_notification(collector=current_user, post_id=post.id, receiver=post.author)
    return redirect(url_for('main.show_post', post_id=post_id))


@main_bp.route('/uncollect/<int:post_id>', methods=['POST'])
@login_required
def uncollect(post_id):
    post = Post.query.get_or_404(post_id)
    if not current_user.is_collecting(post):
        flash('Not collecting.', 'info')
        return redirect(url_for('main.show_post', post_id=post.id))

    current_user.uncollect(post)
    flash('Post uncollected.', 'success')
    return redirect(url_for('main.show_post', post_id=post_id))


@main_bp.route('/post/<int:post_id>/collectors')
@cache.cached(timeout=60)
def show_collectors(post_id):
    post = Post.query.get_or_404(post_id)
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['AWESOME_USER_PER_PAGE']
    pagination = Collect.query.with_parent(post).order_by(Collect.timestamp.desc()).paginate(page, per_page)
    collects = pagination.items
    return render_template('main/collectors.html', pagination=pagination, collects=collects, post=post)


@main_bp.route('/category/<int:category_id>')
@cache.cached(timeout=60)
def show_category(category_id):
    category = Category.query.get_or_404(category_id)
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['AWESOME_POST_PER_PAGE']
    pagination = Post.query.with_parent(category).order_by(Post.timestamp.desc()).paginate(page, per_page)
    posts = pagination.items
    return render_template('main/category.html', pagination=pagination, posts=posts, category=category)


@main_bp.route('/notifications')
@login_required
def show_notifications():
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['AWESOME_NOTIFICATION_PER_PAGE']
    notifications = Notification.query.with_parent(current_user)
    filter_rule = request.args.get('filter')
    if filter_rule == 'unread':
        notifications = notifications.filter_by(is_read=False)

    pagination = notifications.order_by(Notification.timestamp.desc()).paginate(page, per_page)
    notifications = pagination.items
    return render_template('main/notifications.html', pagination=pagination, notifications=notifications)


@main_bp.route('/notification/read/<int:notification_id>', methods=['POST'])
@login_required
def read_notification(notification_id):
    notification = Notification.query.get_or_404(notification_id)
    if current_user != notification.receiver:
        abort(403)

    notification.is_read = True
    db.session.commit()
    flash('Notification read.', 'success')
    return redirect(url_for('.show_notifications'))


@main_bp.route('/notification/read/all', methods=['POST'])
@login_required
def read_all_notifications():
    for notification in current_user.notifications:
        notification.is_read = True
    db.session.commit()
    flash('All notifications read.', 'success')
    return redirect(url_for('.show_notifications'))


@main_bp.route('/avatar/<path:filename>')
def get_avatar(filename):
    return send_from_directory(current_app.config['AVATARS_SAVE_PATH'], filename)


@main_bp.route('/about')
@cache.cached(timeout=3600 * 24)
def about():
    return render_template('main/about.html')


@main_bp.route('/search')
def search():
    q = request.args.get('q', '')
    if q == '':
        flash('Please enter something.', 'warning')
        return redirect_back()

    page = request.args.get('page', 1, type=int)

awesome_flask_webapp/templates/base.html
{% from 'bootstrap/nav.html' import render_nav_item %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% block head %}
        <title>{% block title %} {% endblock title %} - Blog Title </title>
        {% block styles %}
            <link rel="stylesheet" href="https://cdn.staticfile.org/twitter-bootstrap/4.3.1/css/bootstrap.min.css">
            <link rel="stylesheet" href="{{ url_for('static', filename='open-iconic/font/css/open-iconic-bootstrap.css') }}">
            <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
        {% endblock styles %}
    {% endblock head %}
</head>
<body>
{% block navbar %}
    <nav class="navbar navbar-expand-lg bg-light">
            <!-- Logo -->
            <a class="navbar-brand" href="#">
                <img class="avatar-xs" src="{{ url_for('static', filename='github.ico') }}" alt="awesome-webapp">
            </a>
            <!-- collapsible Button -->
            <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#collapsibleNavbar">
                <span class="navbar-toggler-icon"></span>
            </button>
            <!-- collapse -->
            <div class="collapse navbar-collapse" id="collapsibleNavbar">
                <div class="navbar-nav mr-auto">
                    {{ render_nav_item('main.index', 'Home') }}
                    {{ render_nav_item('main.about', 'About') }}
                    <form class="form-inline ml-3 my-0" action="{{ url_for('main.search') }}">
                        <input type="text" class="form-control" name="q" placeholder="Search" required>
                        <button class="btn btn-primary" type="submit">
                            <span class="oi oi-magnifying-glass"></span>
                        </button>
                    </form>
                </div>

                <div class="navbar-nav ml-auto">
                    {% if current_user.is_authenticated %}
                        <a class="nav-item nav-link" href="{{ url_for('main.show_notifications') }}">
                            <span class="oi oi-bell"></span>
                            <span id="notification_count_badge"
                                  class="{% if notification_count == 0 %}hide{% endif %} badge badge-primary badge-notification"
                                    data-href="{{ url_for('ajax.notification_count') }}">
                                {{ notification_count }}
                            </span>
                        </a>
                        <a class="nav-item nav-link" href="{{ url_for('main.new_post') }}">
                            <span class="oi oi-plus"></span>
                        </a>
                        <div class="dropdown nav-item">
                            <a href="#" class="btn nav-link dropdown-toggle" role="button" data-toggle="dropdown">
                                <span class="oi oi-person"></span>
                            </a>
                            <div class="dropdown-menu dropdown-menu-right ">
                                <h6 class="dropdown-header">Username: {{ current_user.username }}</h6>
                                <a class="dropdown-item" href="{{ url_for('user.index', user_id=current_user.id) }}">
                                    <span class="oi oi-home"></span> Home Page
                                </a>
                                <a class="dropdown-item" href="{{ url_for('user.edit_profile') }}">
                                    <span class="oi oi-cog"></span> Settings
                                </a>
                                {% if current_user.can('MODERATE') %}
                                    <a class="dropdown-item" href="{{ url_for('admin.index') }}">
                                        <span class="oi oi-dashboard"></span> Manage
                                    </a>
                                {% endif %}
                                <a class="dropdown-item" href="{{ url_for('auth.logout') }}">
                                    <span class="oi oi-account-logout"></span> Logout
                                </a>
                            </a>
                        </div>
                    {% else %}
                        <a class="btn btn-outline-primary" href="{{ url_for('auth.login') }}">Login</a>&nbsp;&nbsp;
                        <a class="btn btn-primary" href="{{ url_for('auth.register') }}">Register</a>
                    {% endif %}
                </div>
            </div>
    </nav>
{% endblock navbar %}

<main class="container">
    {% for message in get_flashed_messages(with_categories=True) %}
        <div class="alert alert-{{ message[0] }} alert-dismissible fade show">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            {{ message[1] }}
        </div>
    {% endfor %}

    {% block content%} {% endblock content %}

    {% block footer %}
        <footer >
            <p class="float-left" >
                <small>&copy;2020
                    <a href="#">Yeh</a> -
                    <a href="https://github.com/yeh-George/">GitHub</a>
                </small>
            </p>
        </footer>
    {% endblock footer%}
</main>

{% block scripts %}
    <script src="https://cdn.staticfile.org/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdn.staticfile.org/popper.js/1.15.0/umd/popper.min.js"></script>
    <script src="https://cdn.staticfile.org/twitter-bootstrap/4.3.1/js/bootstrap.min.js"></script>
    {{ moment.include_moment(local_js=url_for('static', filename='js/moment-with-locales.min.js')) }}
    <script type="text/javascript" src="{{ url_for('static', filename='js/script.js') }}"></script>
    <script type="text/javascript">
        var csrf_token = "{{ csrf_token() }}";
        {% if current_user.is_authenticated %}
            var is_authenticated = true;
        {% else %}
            var is_authenticated = false;
        {% endif %}
    </script>
{% endblock scripts %}

<div id="toast"></div>

</body>
</html>

awesome_flask_webapp/templates/macros.html
{% macro post_card(post) %}
        <h3 class="text-primary">
            <a href="{{ url_for('main.show_post', post_id=post.id) }}">{{ post.title }}</a>
        </h3>
        <p>
            {{ post.body|striptags|truncate }}
            <small><a href="{{ url_for('main.show_post', post_id=post.id) }}">Read More</a></small>
        </p>
        <small>
            Comments: <a href="{{ url_for('main.show_post', post_id=post.id) }}#comments">{{ post.comments|length }}</a>
            &nbsp;&nbsp;
            Collectors: <a href="{{ url_for('main.show_collectors', post_id=post.id) }}">{{ post.collectors|length }}</a>
            &nbsp;&nbsp;
            Category: <a href="#">{{ post.category.name }}</a>
            <span class="float-right">
                Author: <a href="{{ url_for('user.index', user_id=post.author.id) }}">{{ post.author.username }}</a>&nbsp;&nbsp;
                {{ moment(post.timestamp).format('LL') }}
            </span>
        </small>
{% endmacro %}

{% macro user_card(user) %}
    <div class="user-card text-center">
        <a href="{{ url_for('user.index', user_id=user.id) }}">
            <img class="rounded avatar-m"
                 src="{{ url_for('main.get_avatar', filename=user.avatar_m) }}" alt="{{ user.username }}">
        </a>
        <h6>
            <a href="{{ url_for('user.index', user_id=user.id) }}">{{ user.username }}</a>
        </h6>
        {{ follow_area(user) }}
    </div>
{% endmacro %}

{% macro follow_area(user) %}
    {% if current_user.is_authenticated %}
        {% if current_user != user %}
            {% if current_user.is_following(user) %}
                <form class="inline" method="post"
                  action="{{ url_for('user.unfollow', user_id=user.id, next=request.full_path) }}">
                    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                    <button type="submit" class="btn btn-dark btn-sm">Unfollow</button>
                    {% if current_user.is_followed_by(user) %}
                        <p class="badge badge-light">Follow each other</p>
                    {% endif %}
                </form>
            {% else %}
                <form class="inline" method="post"
                      action="{{ url_for('user.follow', user_id=user.id, next=request.full_path) }}">
                    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                    <button type="submit" class="btn btn-primary btn-sm">Follow</button>
                    {% if current_user.is_followed_by(user) %}
                        <p class="badge badge-light">Follows you</p>
                    {% endif %}
                </form>
            {% endif%}
        {% endif %}
    {% else %}
        <form class="inline" method="post"
              action="#">
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
            <button type="submit" class="btn btn-primary btn-sm">Follow</button>
        </form>
    {% endif %}
{% endmacro %}